{
    'name': 'Odoo-WooCommerce Sync',
    'summary': """Synchronize data between WooCommerce and Odoo.""",
    'description': """Odoo-WooCommerce Sync is a connector add-on for Odoo that synchronizes data between WooCommerce and Odoo.""",
    'license': 'AGPL-3',
    'author': 'roboes',
    'website': 'https://github.com/roboes/odoo-woocommerce-sync',
    'category': 'Connectors',
    # 'version': '16.0.2.7',
    'version': '18.0.2.7',
    # 'version': '19.0.2.7',
    'external_dependencies': {
        'python': ['filetype', 'phonenumbers', 'woocommerce'],
    },
    'depends': ['account', 'contacts', 'delivery', 'product', 'queue_job', 'sale_management', 'stock', 'stock_account'],
    'data': [
        'security/ir.model.access.csv',
        'data/woocommerce.sync.order.status.xml',
        # 'views/v16/product_product_form.xml',
        # 'views/v16/product_product_tree.xml',
        # 'views/v16/product_template_form.xml',
        # 'views/v16/product_template_kanban.xml',
        # 'views/v16/product_template_tree.xml',
        # 'views/v16/res_partner_form.xml',
        # 'views/v16/res_partner_tree.xml',
        # 'views/v16/sale_order_form.xml',
        # 'views/v16/sale_order_tree.xml',
        # 'views/v16/views.xml',
        'views/v18/product_product_form.xml',
        'views/v18/product_product_tree.xml',
        'views/v18/product_template_form.xml',
        'views/v18/product_template_kanban.xml',
        'views/v18/product_template_tree.xml',
        'views/v18/res_partner_form.xml',
        'views/v18/res_partner_tree.xml',
        'views/v18/sale_order_form.xml',
        'views/v18/sale_order_tree.xml',
        'views/v18/views.xml',
        # 'views/v19/product_product_form.xml',
        # 'views/v19/product_product_tree.xml',
        # 'views/v19/product_template_form.xml',
        # 'views/v19/product_template_kanban.xml',
        # 'views/v19/product_template_tree.xml',
        # 'views/v19/res_partner_form.xml',
        # 'views/v19/res_partner_tree.xml',
        # 'views/v19/sale_order_form.xml',
        # 'views/v19/sale_order_tree.xml',
        # 'views/v19/views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'woocommerce_sync/static/src/js/json_html_widget.js',
            'woocommerce_sync/static/src/scss/product_gallery_kanban.scss',
            'woocommerce_sync/static/src/xml/json_html_template.xml',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
